#!/usr/bin/env python3
"""
Generate plain text menu for Slack
Just copy and paste to Slack!
"""

import subprocess
from datetime import datetime
from menu_scraper import scrape_weekly_menu


def generate_slack_text(weekly_menu: list, location: str = "palo-alto") -> str:
    """Generate Slack-formatted text."""
    
    day_names = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
    
    start_date = weekly_menu[0]['date']
    end_date = weekly_menu[-1]['date']
    
    lines = [
        f"🍽️ *{location.replace('-', ' ').title()} Cafeteria - Weekly Lunch Menu*",
        f"📅 {start_date} to {end_date}",
        ""
    ]
    
    for i, menu in enumerate(weekly_menu):
        date_obj = datetime.strptime(menu['date'], '%Y-%m-%d')
        date_display = date_obj.strftime('%m/%d')
        
        lines.append(f"━━━━━━━━━━━━━━━━━━━━━━━")
        lines.append(f"*{day_names[i]} ({date_display})*")
        
        meat = menu.get('meat', [])
        seafood = menu.get('seafood', [])
        other = menu.get('other', [])
        
        # Meat (highlighted)
        if meat:
            lines.append(f"🥩 *Meat*: {'; '.join(meat)}")
        else:
            lines.append(f"🥩 *Meat*: None")
        
        # Seafood (highlighted)
        if seafood:
            lines.append(f"🐟 *Seafood*: {'; '.join(seafood)}")
        else:
            lines.append(f"🐟 *Seafood*: None")
        
        # Other dishes
        if other:
            other_preview = other[:10]  # Show first 10
            other_text = ", ".join(other_preview)
            if len(other) > 10:
                other_text += f" (+{len(other) - 10} more)"
            lines.append(f"🥗 *Other*: {other_text}")
        
        lines.append("")
    
    lines.append("━━━━━━━━━━━━━━━━━━━━━━━")
    lines.append("🔗 Full menu: https://snap-palo-alto.cafebonappetit.com")
    lines.append("🤖 _Auto-generated by Cafe Menu Bot_")
    
    return "\n".join(lines)


def main():
    location = "palo-alto"
    
    print("🍽️  Generating Slack text...")
    print()
    
    weekly_menu = scrape_weekly_menu(location)
    text = generate_slack_text(weekly_menu, location)
    
    # Copy to clipboard
    subprocess.run(['pbcopy'], input=text.encode(), check=True)
    
    print("=" * 50)
    print("SLACK MESSAGE (已复制到剪贴板!):")
    print("=" * 50)
    print()
    print(text)
    print()
    print("=" * 50)
    print("✅ 已复制到剪贴板！直接去 Slack 粘贴即可 (Cmd+V)")
    print("=" * 50)


if __name__ == "__main__":
    main()
